### ISSUE TITLE
Problem with SSL certificate

### ISSUE THREAD

**Issue by jegger06** [jwilsson/spotify-web-api-php#99]
I am currently using wamp and installed this spotify web api wrapper. I am having issues with it. My php version is 7.0.23..

![cert_error](https://user-images.githubusercontent.com/4451929/30794101-dc40edda-a1f8-11e7-9e54-cdc59909b7e6.png)

Can anyone help me with this issue? Thanks.

**Comment by jwilsson** [comment]
Hi!
Could you try with `2.0.1` (which I just published with a new CA certificate bundle). I don't think the issue lies in there but it's worth a shot.

Thanks!

**Comment by jegger06** [comment]
Hello!

I tried installing that version and it is still the same issue. Don't know why.

**Comment by jwilsson** [comment]
Hmm, could you post the following?

* The code that's failing (remove any Spotify client IDs/secrets).
* Your PHP version.
* Your OS.

Thanks!

**Comment by jwilsson** [comment]
I'm gonna close this due to a lack of activity. 

Just let me know if you have any further questions or want it reopened.
